### PR TITLE
Start measuring code coverage

### PR DESCRIPTION
**Pull request by hartwork**
~Sits on top of #50 to avoid conflicts for the moment.~

### CODE REVIEW

**Comment by hartwork** [comment]
Rebased off #50 onto `master` just now.

**Comment by esc** [comment]
So, I gave this a quick try and it seems like the code sections related to the command line interface don't seem to be covered? At least the report seems to indicate this. Current assumption is that this is because the `git_big_picture.py` isn't imported as module. Probably the entry point /setuptools stuff may fix this, but that is just  a guess.  I'll take another look later on tonight.

**Comment by hartwork** [comment]
> So, I gave this a quick try and it seems like the code sections related to the command line interface don't seem to be covered?

Excellent finding! I'll investigate myself too.

**Comment by hartwork** [comment]
> So, I gave this a quick try and it seems like the code sections related to the command line interface don't seem to be covered?

Pretty tricky actually.  Here is what I found with regard to coverage with subprocesses:

Let's create a toy caller and a toy callee, both Python-based:

```console
# cd "$(mktemp -d)"
# echo $'#! /usr/bin/env python\nimport subprocess\nsubprocess.call(["./callee.py"])' > caller.py
# echo $'#! /usr/bin/env python\nimport sys\nprint(f"Hello from {sys.argv}")' > callee.py
# chmod a+x caller.py callee.py
# ./caller.py 
Hello from ['./callee.py']
```

I'll continue in the same shell session everywhere below.

Now let's add coverage on top to find that `./callee.py` is called but not covered:

```console
# python3 -m venv venv
# source venv/bin/activate
# pip install coverage
# echo $'[run]\nomit = venv/*\nsource = .' > .coveragerc
# coverage erase ; coverage run ./caller.py ; coverage report
Hello from ['./callee.py']
Name        Stmts   Miss  Cover
-------------------------------
callee.py       2      2     0%
caller.py       2      0   100%
-------------------------------
TOTAL           4      2    50%
```

To get `./callee.py` covered, we do the three things needed:
- Hook coverage into new processes (see https://coverage.readthedocs.io/en/coverage-5.1/subprocess.html)
- Configure concurrency to be `multiprocessing`
- Pass `COVERAGE_PROCESS_START=.coveragerc` when calling `coverage`.

All three steps are needed, combined things work:

```console
# echo $'try:\n\timport coverage\n\tcoverage.process_startup()\nexcept ImportError:\n\tpass' > "$(ls -1d venv/lib/python*)"/site-packages/sitecustomize.py
# echo $'[run]\nconcurrency = multiprocessing\nomit = venv/*\nsource = .' > .coveragerc
# coverage erase ; COVERAGE_PROCESS_START=.coveragerc coverage run ./caller.py ; coverage combine ; coverage report
Hello from ['./callee.py']
Name        Stmts   Miss  Cover
-------------------------------
callee.py       2      0   100%
caller.py       2      0   100%
-------------------------------
TOTAL           4      0   100%
```

Now what about Scruf?

```console
# pip install scruf
# echo $'#! /usr/bin/env scruf\ncheck callee.py output\n    $ callee.py\n    [RE] Hello from \[.*\]\n    [0]' > test.scf
# chmod a+x test.scf 
# PATH="${PATH}:${PWD}" ./test.scf 
# Testing: ./test.scf
1..1
ok 1 - check callee.py output

# coverage erase ; COVERAGE_PROCESS_START=.coveragerc PATH="${PATH}:${PWD}" coverage run venv/bin/scruf test.scf ; coverage combine ; coverage report
# Testing: test.scf
1..1
ok 1 - check callee.py output
Coverage.py warning: No data was collected. (no-data-collected)
Name        Stmts   Miss  Cover
-------------------------------
callee.py       2      2     0%
caller.py       2      2     0%
-------------------------------
TOTAL           4      4     0%
```

Doesn't work! :thinking:

I have tried _all_ ideas I had for this today already. Any ideas how to continue?

**Comment by hartwork** [comment]
Finally figured it out: We have relative paths in `.coveragerc` and two processes with different working directories, hence the coverage collection in one process was matching against a diferrent understanding of the `source = .` inclusion list. I have implemented a workaround now and also added a longer in-code comment on why the workaround is needed. We're being reported `86%` test coverage now (before #60).

**Comment by hartwork** [comment]
@esc FYI I have reported the observed coverage behavior as a bug upstream now at https://github.com/nedbat/coveragepy/issues/1093 .

**Comment by esc** [comment]
@hartwork 😍👍🔥

**Comment by hartwork** [comment]
Ready to merge?

**Pull request merged**
