### PR TITLE
A few interesting features added

### PR DESCRIPTION
**Pull request by franckspike**
added exclusion file
added inclusion file
added --horizontal option (vertical by default, but has no vertical explicit option…)
added json export (named jsonlt for json light, graphviz now supports exporting to json, but the current Windows version does not include it yet)

maybe you find interesting ideas in this

François

### CODE REVIEW

**Comment by esc** [comment]
@franckspike thank you for submitting this. I think with the significant number of new features some tests will be needed before this can be merged.

**Comment by hartwork** [comment]
The `--horizontal` switch in here seems to be what #36 is asking for.

**Comment by hartwork** [comment]
I have taken the `--horizontal` idea a step further now to support left-to-right, right-to-left and top-to-bottom as well now in #59, keeping one of your commits. Speaking for myself, I believe that's the only part of this pull request we should adopt for the moment to keep complexity low and because we'd need to write tests ourselves for all of the other features while there has been no demand from others about these features in the last ~18 months. I hope that's okay with you for the moment. Thank you! @esc what do you think?

**Comment by esc** [comment]
@hartwork that is great, thank you! @franckspike thank you very much for submitting this. We have adopted the layout direction feature as we deemed it to be interesting and it will be included in the upcoming 1.0.0 release.

**Comment by franckspike** [comment]
@esc with pleasure!

**Pull request closed without merging**
