### PR TITLE
[DO NOT MERGE] Autoformat using black (alternative to #66)

### PR DESCRIPTION
**Pull request by hartwork**
Needs (more or less) all other pull requests to have been merged to not cause painful conflicts.
The idea is to present an earlier version for review now so that I can work on more things concurrently.
Sits on top of pull request #53 to avoid conflicts, that will go away later as well.

PS: For the autoformat commit, maybe an author like `black <black@autoformatter.invalid>` works best. Happy about other suggestions.

Alternative to #66

### CODE REVIEW

**Comment by hartwork** [comment]
@esc after comparing the results of black here and payf in #66 my impression is that black takes a lot more vertical space than seems healthy and needed to me and that yapf is a lot less invasive while still moving us into the 99%-pep8-conformant zone where we mostly can stop thinking about formatting. Are you a strong proponent of black for this code base? I'm tending towards voting for payf over black myself at the moment. (Either would be too early to merge but I think they already serve to give an impression.)

**Comment by esc** [comment]
I'm in two minds about this. 

yapf:

```
    format_group.add_argument('-g',
                              '--graphviz',
                              default=None,
                              action='store_true',
                              dest=GRAPHVIZ,
                              help='output lines suitable as input for dot/graphviz')
```

vs. black:


```

    format_group.add_option(
        '-g',
        '--graphviz',
        action='store_true',
        dest='graphviz',
        help='output lines suitable as input for dot/graphviz',
    )
```

So, for this particular example, I would favour black

**Comment by esc** [comment]
But you are right, yapf seems a lot less invasive, especially in the comments.

**Comment by esc** [comment]
I'm fine with either actually, but also leaning towards yapf, for the same reasons you cite above.

**Comment by hartwork** [comment]
Awesome, let's go for yapf then! Closing the black one here now.

**Pull request closed without merging**
