### PR TITLE
Migrate from unmaintained Cram to maintained Scruf

### PR DESCRIPTION
**Pull request by hartwork**
Just an idea for consideration.

PS: Not sure why GitHub displays the rename as remove and add. Maybe more fun to review locally :thinking:

### CODE REVIEW

**Comment by esc** [comment]
Output looks nice

```
 💣 zsh» PATH="${PATH}:${PWD}" ./test.scf
# Testing: ./test.scf
1..41
ok 1 - no repo
ok 2 - create a fake repo (i.e. global setup for all following tests)
ok 3
ok 4 - run without options
ok 5
ok 6
ok 7 - mix --graphviz and --processed and others
ok 8
ok 9
ok 10
ok 11
ok 12 - try wrong format
ok 13 - mismatch format, filename takes precedence
ok 14
ok 15
ok 16
ok 17 - try just filename
ok 18
ok 19
ok 20
ok 21 - try using different format
ok 22
ok 23
ok 24
ok 25 - try no such viewer
ok 26 - format but no extension
ok 27
ok 28
ok 29
ok 30 - provide filename and viewer
ok 31
ok 32
ok 33
ok 34 - provide filename and viewer and format
ok 35
ok 36
ok 37
ok 38 - try profiling
ok 39
ok 40
ok 41
```

**Comment by esc** [comment]
Probably that output could be unified and made to look prettier.

**Comment by esc** [comment]
FWIW: here is a different project of mine that combines use of cram and coverage. It uses a bootstrapping shell script, however: https://github.com/Blosc/bloscpack/blob/master/test_cmdline/cram_strap.sh

**Comment by hartwork** [comment]
> Probably that output could be unified and made to look prettier.

Please elaborate. In particular, are you  speaking *inside* this pull request or *optionally later*?

**Comment by esc** [comment]
> > Probably that output could be unified and made to look prettier.
> 
> Please elaborate. In particular, are you speaking about _inside_ this pull request or _optionally later_?

I mean, making the titles proper titles with punctuation and caps and using coherent language (always starting a sentence for testing an error handling case with `try`:

```
ok 30 - Try to provide filename and viewer.
ok 31
ok 32
ok 33
ok 34 - Try to provide filename and viewer and format.
ok 35
ok 36
ok 37
ok 38 - Try profiling.
```

**Comment by hartwork** [comment]
> In case you are already thinking about running coverage too.

That's in #61 already.

**Comment by hartwork** [comment]
> I mean, making the titles proper titles with punctuation and caps and using coherent language (always starting a sentence for testing an error handling case with `try`):

Okay, sure! Can we agree to do that after #50 is merged? Who should do the PR — you or me?

**Comment by esc** [comment]
> > In case you are already thinking about running coverage too.
> 
> That's in #61 already.

Oh great! Hadn't seen that yet.

**Comment by esc** [comment]
> > I mean, making the titles proper titles with punctuation and caps and using coherent language (always starting a sentence for testing an error handling case with `try`):
> 
> Okay, sure! Can we agree to do that after #50 is merged? Who should do the coherent language PR — you or me?

Yes, let's prettify later, get this in first and I'll take care of the rewording.

**Comment by hartwork** [comment]
> Yes, let's prettify later, get this in first and I'll take care of the rewording.

Cool!

**Review by esc — APPROVED** [review]
I tried it locally, it works fine. I tried manually breaking the tests, Scruf fails and exists with a non-zero error code. All of it looks good to me. Please feel free to merge when ready.

**Pull request merged**
