### PR TITLE
Fix argument --processed (fixes #197) + release 1.2.1

### LINKED ISSUE #197: [>=0.10.0] Argument --processed stopped producing healthy output
What is the purpose of --processed option nowadays? It used to output the big picture in the requested format; v1.2.0 outputs a Python bytes literal which IMHO makes no sense. Please see below:
```
$ ./git-big-picture-v0.9.0 --format=svg -pVO | xmllint -noout -
$ git big-picture --format=svg -pVO | xmllint -noout -
-:1: parser error : Start tag expected, '<' not found
b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "
^
```
I found the old behavior useful and sane.

Br. Sami

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #197

CC @oCCtet

### CODE REVIEW

**Review by esc — APPROVED** [review]
LGTM and thank you for the quick fix! All tests are passing it seems. Maybe we can get a confirmation from @oCCtet too and then it'll be good to release.

**Comment by oCCtet** [comment]
I can confirm the fix works okay. Tested svg, pdf and png formats.

**Comment by hartwork** [comment]
@oCCtet thanks!

**Comment by hartwork** [comment]
1.2.1 released to Git and PyPI now

**Comment by esc** [comment]
> PS: @esc do we need an entry for #198 in the change log? I'm tending towards "no" myself at the moment.

OK!

**Pull request merged**
