### PR TITLE
Migrate back to Cram

### PR DESCRIPTION
**Pull request by hartwork**
Motivation being:
- Scruf is okay with the command producing more output than we check for. You @esc and I both hit that by surprise, I consider it annoying and an unfixed bug (or design issue) in Scruf.
- nixOS seems to want to take test requirements into account, they don't have Scruf packaged and I'm not the best person to package it for nixOS; ~so getting off Scruf may help unblocking https://github.com/NixOS/nixpkgs/pull/109569~

Other aspects:
- Cram is unmaintained but we are not aware of any relevant bugs or incompatibilities of Cram yet

### CODE REVIEW

**Comment by esc** [comment]
@hartwork I am fine with either. I would suggest keeping both? It is hard today how the competition between the two will play out and I don't want to place my bets on the wrong horse. What do you think?

**Comment by hartwork** [comment]
> @hartwork I am fine with either. I would suggest keeping both? It is hard today how the competition between the two will play out and I don't want to place my bets on the wrong horse. What do you think?

I see more downsides with keeping both than upsides: We'd have to keep both maintained, we would still need to keep Scruf out of the dependencies for nixOS or get someone package it. If you have a weird feeling about going back to Cram, I can spend time migrating the whole to thing to plain unittest, instead: Most test would still test the command's output, they just would read a bit less like shell session. Maybe that's okay.

What do you think?

**Comment by esc** [comment]
> > @hartwork I am fine with either. I would suggest keeping both? It is hard today how the competition between the two will play out and I don't want to place my bets on the wrong horse. What do you think?
> 
> I see more downsides with keeping both than upsides: We'd have to keep both maintained, we would still need to keep Scruf out of the dependencies for nixOS or get someone package it. If you have a weird feeling about going back to Cram, I can spend time migrating the whole to thing to plain unittest, instead: Most test would still test the command's output, they just would read a bit less like shell session. Maybe that's okay.
> 
> What do you think?

OK, in that case, probably staying with cram is best. It's not too hard to switch back and forth anyway , so if scruf gains more traction, we can always switch back to that.

**Comment by hartwork** [comment]
Okay, so Cram again for now.

**Comment by esc** [comment]
> Okay, so Cram again for now.

👍

**Pull request merged**
